INSERT INTO DEDELER.CATEGORY (CATEGORYNAME) 
	VALUES ('Karadeniz');
INSERT INTO DEDELER.CATEGORY (CATEGORYNAME) 
	VALUES ('Ege');
INSERT INTO DEDELER.CATEGORY (CATEGORYNAME) 
	VALUES ('Burger');
INSERT INTO DEDELER.CATEGORY (CATEGORYNAME) 
	VALUES ('Pizza');
INSERT INTO DEDELER.CATEGORY (CATEGORYNAME) 
	VALUES ('Döner');
INSERT INTO DEDELER.CATEGORY (CATEGORYNAME) 
	VALUES ('Pide');
INSERT INTO DEDELER.CATEGORY (CATEGORYNAME) 
	VALUES ('Tatlı');
INSERT INTO DEDELER.CATEGORY (CATEGORYNAME) 
	VALUES ('Antep');
INSERT INTO DEDELER.CATEGORY (CATEGORYNAME) 
	VALUES ('Et');