INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Akin', 'Özer', 'akinozer@ourmail.com', '05325553312', 15);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Ahmet', 'Demirtaş', 'ahmetdemirtas@ourmail.com', '05052226732', 16);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Semih', 'Sevinçli', 'semihsevincli@ourmail.com', '05552345678', 17);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Süleyman Gökhan', 'Birkin', 'gokhanbirkin@ourmail.com', '05065123454', 18);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Adem', 'Uçar', 'ademucar@ourmail.com', '05431234567', 19);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Elif', 'Gezgin', 'elihgezgşn@ourmail.com', '05453334566', 20);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Hilal', 'Demirtaş', 'hilaldemirtas@ourmail.com', '05543211123', 21);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Zafer', 'Büyükkılıç', 'zaferbuyukkilic@ourmail.com', '05543456732', 22);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Aslı', 'Kaya', 'aslikaya@ourmail.com', '05433345619', 23);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Harun', 'Demir', 'harundemir@ourmail.com', '05333457433', 24);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Taynur', 'Arslan', '@tayfurarslanourmail.com', '05456783654', 25);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Melek', 'Pancar', 'melekpancar@ourmail.com', '05053451231', 26);
INSERT INTO DEDELER.CUSTOMER (PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ADDRESSID) 
	VALUES ('dedeler', 'Cemil', 'Bolu', 'cemilbolu@ourmail.com', '05067532215', 27);