INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Burger King', 'burgerking@mymail.com', '05057771122', 1, 'Burger');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Abbas Waffle', 'abbaswaffle@mymail.com', '053211122233', 2, 'Tatlı');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Antep Sofrası', 'antepsofrasi@mymail.com', '05332221144', 3, 'Antep');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Ramiz Usta', 'ramizusta@mymail.com', '05442345612', 4, 'Et');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Etiler Marmaris', 'etilermarmaris@mymail.com', '05442221133', 5, 'Burger');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Hünkar Döner', 'hunkardoner@mymail.com', '05433332245', 6, 'Döner');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Egelim', 'egelim@mymail.com', '02124453321', 7, 'Ege');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Abide Kebap', 'abide@mymail.com', '05325564321', 8, 'Antep');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Big Mamas', 'bigmamas@mymail.com', '05556678932', 9, 'Et');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Seventeen Pizza', 'seventeenpizza@mymail.com', '05432221167', 10, 'Pizza');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Nur Abla', 'nurabla@mymail.com', '05358763212', 11, 'Karadeniz');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'Çiçek Izgara', 'cicekizgara@mymail.com', '05545632211', 12, 'Et');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'İskender', 'iskender@mymail.com', '05345623344', 13, 'Döner');
INSERT INTO DEDELER.RESTAURANT (PASSWORD, RESTAURANTNAME, EMAIL, PHONENUMBER, ADDRESSID, CATEGORYNAME) 
	VALUES ('dedeler', 'NGS', 'ngs@mymail.com', '05354271364', 14, 'Tatlı');